define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.localeDefinitions = void 0;
    exports.localeDefinitions = {
        'ca-ES': {
            decimal: ",",
            thousands: ".",
            grouping: [3],
            currency: ["", " €"],
            dateTime: "%A, %e de %B de %Y, %X",
            date: "%d/%m/%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["diumenge", "dilluns", "dimarts", "dimecres", "dijous", "divendres", "dissabte"],
            shortDays: ["dg.", "dl.", "dt.", "dc.", "dj.", "dv.", "ds."],
            months: ["gener", "febrer", "març", "abril", "maig", "juny", "juliol", "agost", "setembre", "octubre", "novembre", "desembre"],
            shortMonths: ["gen.", "febr.", "març", "abr.", "maig", "juny", "jul.", "ag.", "set.", "oct.", "nov.", "des."]
        },
        'de-DE': {
            decimal: ",",
            thousands: ".",
            grouping: [3],
            currency: ["", " €"],
            dateTime: "%A, der %e. %B %Y, %X",
            date: "%d.%m.%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
            shortDays: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
            months: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
            shortMonths: ["Jan", "Feb", "Mrz", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"]
        },
        'en-GB': {
            decimal: ".",
            thousands: ",",
            grouping: [3],
            currency: ["£", ""],
            dateTime: "%a %e %b %X %Y",
            date: "%d/%m/%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            shortDays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
            months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            shortMonths: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        },
        'en-US': {
            decimal: ".",
            thousands: ",",
            grouping: [3],
            currency: ["$", ""],
            dateTime: "%a %b %e %X %Y",
            date: "%m/%d/%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            shortDays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
            months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
            shortMonths: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        },
        'es-ES': {
            decimal: ",",
            thousands: ".",
            grouping: [3],
            currency: ["", " €"],
            dateTime: "%A, %e de %B de %Y, %X",
            date: "%d/%m/%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["domingo", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado"],
            shortDays: ["dom", "lun", "mar", "mié", "jue", "vie", "sáb"],
            months: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
            shortMonths: ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"]
        },
        'fi-FI': {
            decimal: ",",
            thousands: "\xa0",
            grouping: [3],
            currency: ["", "\xa0€"],
            dateTime: "%A, %-d. %Bta %Y klo %X",
            date: "%-d.%-m.%Y",
            time: "%H:%M:%S",
            periods: ["a.m.", "p.m."],
            days: ["sunnuntai", "maanantai", "tiistai", "keskiviikko", "torstai", "perjantai", "lauantai"],
            shortDays: ["Su", "Ma", "Ti", "Ke", "To", "Pe", "La"],
            months: ["tammikuu", "helmikuu", "maaliskuu", "huhtikuu", "toukokuu", "kesäkuu", "heinäkuu", "elokuu", "syyskuu", "lokakuu", "marraskuu", "joulukuu"],
            shortMonths: ["Tammi", "Helmi", "Maalis", "Huhti", "Touko", "Kesä", "Heinä", "Elo", "Syys", "Loka", "Marras", "Joulu"]
        },
        'fr-FR': {
            decimal: ",",
            thousands: ".",
            grouping: [3],
            currency: ["", " €"],
            dateTime: "%A, le %e %B %Y, %X",
            date: "%d/%m/%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
            shortDays: ["dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
            months: ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
            shortMonths: ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."]
        },
        'mk-MK': {
            decimal: ",",
            thousands: ".",
            grouping: [3],
            currency: ["", " ден."],
            dateTime: "%A, %e %B %Y г. %X",
            date: "%d.%m.%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["недела", "понеделник", "вторник", "среда", "четврток", "петок", "сабота"],
            shortDays: ["нед", "пон", "вто", "сре", "чет", "пет", "саб"],
            months: ["јануари", "февруари", "март", "април", "мај", "јуни", "јули", "август", "септември", "октомври", "ноември", "декември"],
            shortMonths: ["јан", "фев", "мар", "апр", "мај", "јун", "јул", "авг", "сеп", "окт", "ное", "дек"]
        },
        'pt-BR': {
            decimal: ',',
            thousands: '.',
            grouping: [3],
            currency: ['R$', ''],
            dateTime: '%A, %e de %B de %Y. %X',
            date: '%d/%m/%Y',
            time: '%H:%M:%S',
            periods: ['AM', 'PM'],
            days: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
            shortDays: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
            months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            shortMonths: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
        },
        'zh-CN': {
            decimal: ".",
            thousands: ",",
            grouping: [3],
            currency: ["¥", ""],
            dateTime: "%a %b %e %X %Y",
            date: "%Y/%-m/%-d",
            time: "%H:%M:%S",
            periods: ["上午", "下午"],
            days: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
            shortDays: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
            months: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
            shortMonths: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"]
        },
        'sv-SE': {
            decimal: ",",
            thousands: " ",
            grouping: [3],
            currency: ["SEK"],
            dateTime: "%A, %e %B %Y, %X",
            date: "%d:%m:%Y",
            time: "%H:%M:%S",
            periods: ["AM", "PM"],
            days: ["måndag", "tisdag", "onsdag", "torsdag", "fredag", "lördag", "söndag"],
            shortDays: ["mån", "tis", "ons", "tor", "fre", "lö", "sö"],
            months: ["Januari", "Februari", "Mars", "April", "Maj", "Juni", "Juli", "Augusti", "September", "Oktober", "November", "December"],
            shortMonths: ["jan", "feb", "mar", "apr", "maj", "jun", "jul", "aug", "sep", "okt", "nov", "dec"]
        },
        'ru-RU': {
            decimal: ",",
            thousands: ".",
            grouping: [3],
            currency: ["", "руб"],
            dateTime: "%A, %e %B %Y, %X",
            date: "%d.%m.%Y",
            time: "%Ч:%М:%С",
            periods: ["AM", "PM"],
            days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
            shortDays: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
            months: ["Январь", "Februar", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
            shortMonths: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"]
        }
    };
});
//# sourceMappingURL=d3Localization.js.map