import ComponentRegistry = require("./componentRegistry");

class CustomComponentRegistry {
    public static register() {
        // Add here custom component registrations following the pattern:
        // return new ComponentRegistry("src/customComponents")
        //              .mapComponent("componentName")

        return new ComponentRegistry("src/customComponents")
            .mapComponent("custom-value")
            .mapComponent("custom-value-component", "custom-value.component")
            .mapComponent("wf-demo-bhkw")
            .mapComponent("wf-demo-hvac")
            .mapComponent("wf-demo-building")
            .mapComponent("wf-demo-production-unit")
            .mapComponent("wf-demo-production-unit-1")
            .mapComponent("wf-demo-production-unit-2")
            .mapComponent("ccw-wf-value")
            .mapComponent("ccw-wf-input-tastatur")
            .mapComponent("ccw-wf-input-tastatur-2")
            .mapComponent("ccw-wf-date-time-picker-s7dt")
            .mapComponent("ccw-wf-date-time-picker-s7bytes")
            .mapComponent("ccw-wf-date-time-picker-s7datetime")
            .mapComponent("ccw-wf-date-time-picker-s7time")
            .mapComponent("ccw-wf-motor0")
            .mapComponent("ccw-wf-motor0a")
            .mapComponent("ccw-wf-motor1")
            .mapComponent("ccw-wf-motor2")
            .mapComponent("ccw-wf-motor3")
            .mapComponent("ccw-wf-motor4")
            .mapComponent("ccw-wf-motor5")
            .mapComponent("ccw-wf-fan0")
            .mapComponent("ccw-wf-fan1")
            .mapComponent("ccw-wf-fan2")
            .mapComponent("ccw-wf-fan3")
            .mapComponent("ccw-wf-fan4")
            .mapComponent("ccw-wf-handventil2")
            .mapComponent("ccw-wf-handventil20")
            .mapComponent("ccw-wf-pump0")
            .mapComponent("ccw-wf-ventil2")
            .mapComponent("ccw-wf-ventil2b")
            .mapComponent("ccw-wf-ventil2c")
            .mapComponent("ccw-wf-ventil2mo")
            .mapComponent("ccw-wf-ventil2mu")
            .mapComponent("ccw-wf-ventil2ml")
            .mapComponent("ccw-wf-ventil2mr")
            .mapComponent("ccw-wf-ventil3")
            .mapComponent("ccw-wf-ventil3mo")
            .mapComponent("ccw-wf-ventil3mu")
            .mapComponent("ccw-wf-ventil3ml")
            .mapComponent("ccw-wf-ventil3mr")
            .mapComponent("ccw-wf-ventil4")
            .mapComponent("ccw-wf-buffer-button2")
            .mapComponent("ccw-wf-weiche0")
            .mapComponent("ccw-gausche")
            .mapComponent("ccw-gausche-waage")            
            .mapComponent("ccw-wf-chart-1", "ccw-wf-chart-1.component")
            .mapComponent("ccw-wf-shape")
            .mapComponent("ccw-wf-action")
            .mapComponent("rez-info", "rez-info.component")
            .mapComponent("rez-info-schmal", "rez-info-schmal.component")
            .mapComponent("rez-dlg", "rez-dlg.component")
            .mapComponent("ccw-wf-sps-stoer-kommunikation")
            .mapComponent("ccw-wf-watchdog", "ccw-wf-watchdog.component")             
            .mapComponent("rez-dlg-rez-only", "rez-dlg-rez-only.component")
            .mapComponent("rez-dlg-pa-only", "rez-dlg-pa-only.component")
            .mapComponent("ccw-wf-bargraph", "ccw-wf-bargraph.component")
            .mapComponent("ccw-wf-user-manager", "ccw-wf-user-manager.component")
            .mapComponent("ccw-wf-um-user-actions", "ccw-wf-um-user-actions/ccw-wf-um-user-actions.component")
            .mapComponent("ccw-wf-um-filter-dialog", "ccw-wf-um-user-actions/ccw-wf-um-filter-dialog.component")
            .mapComponent("ccw-wf-um-time-interval-dialog", "ccw-wf-um-user-actions/ccw-wf-um-time-interval-dialog.component")
            .mapComponent("ccw-load-svg")

            ;
    }
}

export = CustomComponentRegistry;